### Basic Syntax

In [5]:
import numpy as np

In [14]:
a = np.array([1,2,3], dtype = 'int16')
print(a)

[1 2 3]


In [7]:
b = np.array([[9.2,6.3,3.8],[5.7,2.7,3.9]])
print(b)

[[9.2 6.3 3.8]
 [5.7 2.7 3.9]]


In [19]:
print(a.ndim) #Dimension of the array
print(b.ndim)
print(a.shape) 
print(b.shape) #rows X columns
print(a.dtype) #Data type
print(b.dtype)

1
2
(3,)
(2, 3)
int16
float64


In [18]:
print(a.size)  #Number of elements in the array
print(a.itemsize) #Number of bytes one element takes

3
2


### Array Initializing

In [20]:
x = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(x)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [22]:
print(x[1,5])  #Get element at (r,c)

13


In [24]:
print(x[0,:]) #Getting  row 0

[1 2 3 4 5 6 7]


In [26]:
print(x[:,2]) #Getting column 2

[ 3 10]


In [27]:
x[0, 1:6:2]  # 0 selects the row 0 then 1 is starting index 6 is ending index not included and 2 is step size

array([2, 4, 6])

In [29]:
x[1,5] = 20 #Changing a particular element
x[:,2] = [1,2] #Changing elements at column 2 sub-sequence should be of the same dimension
print(x)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [32]:
z = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) #3-d array example
z

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [34]:
z[0,1,1]  #Getting an element work outside in 

4

In [38]:
z[:,1,:] = [[9,9],[8,8]]  #To replace again sub-sequence is exactly the same 
z

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [40]:
np.zeros((2,3))  #All zeroes matrix 2 is number of rows and 3 is number of columns

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
np.ones((4,2,2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [43]:
np.full((2,2), 99)  #Besides 2,2 we can pass shape of prexisting array

array([[99, 99],
       [99, 99]])

In [45]:
np.random.rand(4,2)  # 4 x 2 matrix with random numbers

array([[0.2248766 , 0.3474038 ],
       [0.41588364, 0.75939467],
       [0.88459367, 0.72446728],
       [0.78051297, 0.17838477]])

In [46]:
np.random.random_sample(x.shape)

array([[0.68072603, 0.0771147 , 0.41771953, 0.64261869, 0.55142371,
        0.7889818 , 0.00919625],
       [0.3390361 , 0.88425663, 0.65888781, 0.2050702 , 0.25421146,
        0.85715802, 0.47813547]])

In [48]:
np.random.randint(7,size=(3,3))  # 7 is ending point
np.random.randint(2,7,size=(3,3)) #Values between 2 and 7

array([[4, 3, 4],
       [6, 2, 2],
       [5, 5, 5]])

In [49]:
np.identity(5) #Identity matrix of 5 x 5 size

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [61]:
ans = np.ones((5,5), dtype = 'int32')
temp = np.zeros((3,3))
temp[1,1] = 9
ans[1:4,1:4] = temp  #1:4 is selecting 1st row to 3rd row then 1st column to 3rd column
print(ans)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### Mathematics

In [64]:
m  = np.array([1,2,3,4])
print(m)

[1 2 3 4]


In [87]:
m + 2 # This returns a new array m is still unchanged if m += 2 then m gets changed

array([5, 6, 7, 8])

In [88]:
m - 2

array([1, 2, 3, 4])

In [89]:
m * 2

array([ 6,  8, 10, 12])

In [90]:
m / 2

array([1.5, 2. , 2.5, 3. ])

In [91]:
m // 2

array([1, 2, 2, 3], dtype=int32)

In [93]:
n = np.array([1,1,1,1])
m + n

array([4, 5, 6, 7])

In [94]:
m ** 2

array([ 9, 16, 25, 36])

In [95]:
np.sin(m)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

### Linear Algebra

In [96]:
a = np.ones((2,3))  # Matrix multiplication
print(a)
b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [97]:
c = np.identity(3) 
np.linalg.det(c) # Determinant 

1.0

### Stats

In [99]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
np.min(stats)

1

In [102]:
np.max(stats)

6

In [104]:
np.min(stats, axis = 1) # min of each row

array([1, 4])

In [105]:
np.sum(stats)

21

In [106]:
np.sum(stats, axis = 0) # axis = 0 mein downward jaate hain har bar

array([5, 7, 9])

### Reorganizing Arrays

In [108]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [110]:
v1 = np.array([1,2,3,4])  #Literally vertically stack karna dimesions match hone chaiye par
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [111]:
h1 = np.ones((2,4))   # Horizontal stacking
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])